#!/bin/bash
a=あアいイうウえエおオ
k=かカきキくクけケこコ
s=さサしシすスせセそソ
t=たタちチつツてテとト
n=なナにニぬヌねネのノ
h=はハひヒふフへヘほホ
m=まマみミむムめメもモ
y=やヤゆユよヨ
r=らラりリるルれレろロ
w=わワをヲ
N=んン
g=がガぎギぐグげゲごゴ
z=ざじずぜぞザジズゼゾ
d=だぢづでどダヂヅデド
b=ばびぶべぼバビブベボ
p=ぱぴぷぺぽパピプペポ
all=$a$k$s$t$n$h$m$y$r$w$N$g$z$d$b$p
default_num=12
if [ -z $1 ];then
	echo "请输入参数"
	exit
elif [ -n "$(sed -nr '/^[-akstnhmyrwNgzdbp|(all|-all)]+$/p' <<< $1)" ];then
	echo '' > /dev/null
else
	echo "请输入正确的参数"
	exit
fi

if_num(){
	if [ -n "$(echo $1 | sed -nr '/^[0-9]+$/p')" ];then
                echo $1
	else 
                echo no_num
        fi
}

show_single(){
        for((i=1;i<=$2;i++))
        do
                alpha=$1
                length=$(expr length $alpha)
                n=$[ $RANDOM % $length ]
		x=${alpha:n:1}
                c=$c$x'  '
        done
        echo $c
}

while [ -n "$1" ]
do
	case "$1" in 
		-a|a) 
			if_num=$(if_num $2)
			if [ $if_num == 'no_num' ];then
				if_num=$default_num
				shift
			else
				shift
				shift
			fi
			arg=$(show_single $a $if_num)
			echo $arg;;
		-k|k)
                        if_num=$(if_num $2)
                        if [ $if_num == 'no_num' ];then
				if_num=$default_num
                                shift
                        else
                                shift
                                shift
                        fi
                        arg=$(show_single $k $if_num)
                        echo $arg;;
                -s|s)
                        if_num=$(if_num $2)
                        if [ $if_num == 'no_num' ];then
                                if_num=$default_num
                                shift
                        else
                                shift
                                shift
                        fi
                        arg=$(show_single $s $if_num)
                        echo $arg;;
                -t|t)
                        if_num=$(if_num $2)
                        if [ $if_num == 'no_num' ];then
                                if_num=$default_num
                                shift
                        else
                                shift
                                shift
                        fi
                        arg=$(show_single $t $if_num)
                        echo $arg;;
                -n|n)
                        if_num=$(if_num $2)
                        if [ $if_num == 'no_num' ];then
                                if_num=$default_num
                                shift
                        else
                                shift
                                shift
                        fi
                        arg=$(show_single $n $if_num)
                        echo $arg;;
                -h|h)
                        if_num=$(if_num $2)
                        if [ $if_num == 'no_num' ];then
                                if_num=$default_num
                                shift
                        else
                                shift
                                shift
                        fi
                        arg=$(show_single $h $if_num)
                        echo $arg;;
                -m|m)
                        if_num=$(if_num $2)
                        if [ $if_num == 'no_num' ];then
                                if_num=$default_num
                                shift
                        else
                                shift
                                shift
                        fi
                        arg=$(show_single $m $if_num)
                        echo $arg;;
                -y|y)
                        if_num=$(if_num $2)
                        if [ $if_num == 'no_num' ];then
                                if_num=$default_num
                                shift
                        else
                                shift
                                shift
                        fi
                        arg=$(show_single $y $if_num)
                        echo $arg;;
                -r|r)
                        if_num=$(if_num $2)
                        if [ $if_num == 'no_num' ];then
                                if_num=$default_num
                                shift
                        else
                                shift
                                shift
                        fi
                        arg=$(show_single $r $if_num)
                        echo $arg;;
                -w|w)
                        if_num=$(if_num $2)
                        if [ $if_num == 'no_num' ];then
                                if_num=$default_num
                                shift
                        else
                                shift
                                shift
                        fi
                        arg=$(show_single $w $if_num)
                        echo $arg;;
                -N|N)
                        if_num=$(if_num $2)
                        if [ $if_num == 'no_num' ];then
                                if_num=$default_num
                                shift
                        else
                                shift
                                shift
                        fi
                        arg=$(show_single $N $if_num)
                        echo $arg;;
                -g|g)
                        if_num=$(if_num $2)
                        if [ $if_num == 'no_num' ];then
                                if_num=$default_num
                                shift
                        else
                                shift
                                shift
                        fi
                        arg=$(show_single $g $if_num)
                        echo $arg;;
                -z|z)
                        if_num=$(if_num $2)
                        if [ $if_num == 'no_num' ];then
                                if_num=$default_num
                                shift
                        else
                                shift
                                shift
                        fi
                        arg=$(show_single $z $if_num)
                        echo $arg;;
                -d|d)
                        if_num=$(if_num $2)
                        if [ $if_num == 'no_num' ];then
                                if_num=$default_num
                                shift
                        else
                                shift
                                shift
                        fi
                        arg=$(show_single $d $if_num)
                        echo $arg;;
                -b|b)
                        if_num=$(if_num $2)
                        if [ $if_num == 'no_num' ];then
                                if_num=$default_num
                                shift
                        else
                                shift
                                shift
                        fi
                        arg=$(show_single $b $if_num)
                        echo $arg;;
                -p|p)
                        if_num=$(if_num $2)
                        if [ $if_num == 'no_num' ];then
                                if_num=$default_num
                                shift
                        else
                                shift
                                shift
                        fi
                        arg=$(show_single $p $if_num)
                        echo $arg;;
                -all|all)
                        if_num=$(if_num $2)
                        if [ $if_num == 'no_num' ];then
                                if_num=$default_num
                                shift
                        else
                                shift
                                shift
                        fi
                        arg=$(show_single $all $if_num)
                        echo $arg;;
		*)	
			string=$1
			length=${#string}
			total_str=
			for ((i=1;i<=$length;i++))
			do
				alpha=$(echo $1 | awk -v x=$i '{split($0,a,"");print a[x]}')
				case "$alpha" in 
					a) total_str=$total_str$a;;
					k) total_str=$total_str$k;;
					s) total_str=$total_str$s;;
					t) total_str=$total_str$t;;
					n) total_str=$total_str$n;;
					h) total_str=$total_str$h;;
					m) total_str=$total_str$m;;
					y) total_str=$total_str$y;;
					r) total_str=$total_str$r;;
					w) total_str=$total_str$w;;
					N) total_str=$total_str$N;;	
					g) total_str=$total_str$g;;
					z) total_str=$total_str$z;;
					d) total_str=$total_str$d;;
					b) total_str=$total_str$b;;
					p) total_str=$total_str$p;;
					*) total_str=$total_str;;
				esac	
			done
			if_num=$(if_num $2)
                        if [ $if_num == 'no_num' ];then
                                if_num=$default_num
                                shift
                        else
                                shift
                                shift
                        fi
			arg=$(show_single $total_str $if_num)
			echo $arg;;
	esac
done




